#**Assignment 5**

Use the method we discussed about in the lesson to solve **Example D**. (First presentation: wall with brick and plasters!)

* Remember do it as slow as possible first (very small steps and print them). So that you would understand each step!

* Use ## headers and comments in your Jupyter notebook to make them more readable for yourself and others!
 

##Importing the **NUMPY** package to use the vectorize calculation

In [96]:
import numpy as np

##Input data in the form of **ARRAYS**

First, we can calculate the surface area of each part, and put them in single variables:

In [97]:
A_sec = 1*0.25
A_brick = 1*0.22
A_updown = 1*0.015

Then, we can calculate arrays of 8 separate members, and assign the input data related to each thermal resistance:

In [98]:
RName = np.array(["R_in","R_foam","R_plasterLeft","R_plasterUp","R_brick","R_plasterDown","R_plasterRight","R_out"])
RType = np.array(["conv","cond","cond","cond","cond","cond","cond","conv"])
RConfig = np.array(["serie","serie","serie","parallel","parallel","parallel","serie","serie"])
A = np.array([A_sec,A_sec,A_sec,A_updown,A_brick,A_updown,A_sec,A_sec])
k = np.array([None,0.026,0.22,0.22,0.72,0.22,0.22,None])
h = np.array([10,None,None,None,None,None,None,40])
L = np.array([None,0.03,0.02,0.16,0.16,0.16,0.02,None])

Finally, we can define an array of *0* for the values of unit thermal resistances as they are not yet calculated:

In [99]:
R = np.zeros(8)

##Calculation of each thermal resistance

By the means of **boolean values**, we can reach the members of each list related to the conductive resistances. On the other words, instead of putting the indices for the list to reach the corrosponding values, we can use boolean values related to the **type of the resistances (RType)**:

In [100]:
R_cond = L[RType == "cond"]/A[RType == "cond"]/k[RType == "cond"]
R_cond

array([4.615384615384616, 0.36363636363636365, 48.48484848484849,
       1.0101010101010102, 48.48484848484849, 0.36363636363636365],
      dtype=object)

With the same approach, we can calculate the convective thermal resistances. In fact, now we are considering boolean values related to the convective thermal resistance types:

In [101]:
R_conv = 1/A[RType == "conv"]/h[RType == "conv"]
R_conv

array([0.4, 0.1], dtype=object)

Finally, we can put the values in the array that we previously defined for the thermal resistance values. We fill the 0 members of **R** array such that for the inices that are conductive, the conductive thermal resistance values fill the vacency, and simillar procedure for the convective thermal resistances:

In [102]:
R[RType == "cond"] = R_cond
R[RType == "conv"] = R_conv
np.round(R,4)

array([ 0.4   ,  4.6154,  0.3636, 48.4848,  1.0101, 48.4848,  0.3636,
        0.1   ])

##Calculation of total thermal resistance

First, we calculate the equivalent thermal resistance of the 3 parallel resistances.
As we defined the a **configuration array (RConfig)**, we can use the boolean values as the indexes of "R" array, to reach the paralell ones.
We can use a for loop for doing the inverse summatin of the values:

In [103]:
R_parallel_inv=0

for anyObj in R[RConfig == "parallel"]:
  R_parallel_inv += 1/anyObj

R_parallel = 1/ R_parallel_inv
round(R_parallel,4)

0.9697

Finally, we can sum all the remain thermal resistances that are in series and reach the final value of the total thermal resistanc:

In [104]:
R_tot = R[RConfig == "serie"].sum() + R_parallel
print("The total thermal resistance is: " + str(round(R_tot,4)) + " [degreeC/W]")

The total thermal resistance is: 6.8124 [degreeC/W]


##Calculation of the rate of heat transfer through the wall

In [105]:
deltaT = 20-(-10)
A_wall = 3*5
A_unit = 0.25*1
Q_dot = (A_wall/A_unit)*deltaT/R_tot
print("The rate of heat transfer is: " + str(round(Q_dot,2)) + " [W]")

The rate of heat transfer is: 264.23 [W]
